from typing import List, Dict, Any

SIMULATED_PATIENTS: List[Dict[str, Any]] = [
    {
        "stay_id": 3001,
        "subject_id": 1001,
        "name": "James Wilson (Critical Trauma)",
        "age": 42,
        "gender": "Male",
        "temperature": 97.2,
        "heartrate": 138,
        "resprate": 30,
        "o2sat": 86,
        "sbp": 78,
        "dbp": 45,
        "pain": "10",
        "chiefcomplaint": "CAR VS POLE, MVC WITH FLAIL CHEST AND SEVERE HYPOXIA, RESPIRATORY DISTRESS",
        "is_returning_patient": True,
        "prior_medical_history": "No prior ED visits."
    },
    {
        "stay_id": 3002,
        "subject_id": 1002,
        "name": "Elena Rostova (Stroke / Facial Droop)",
        "age": 68,
        "gender": "Female",
        "temperature": 98.4,
        "heartrate": 92,
        "resprate": 18,
        "o2sat": 97,
        "sbp": 185,
        "dbp": 105,
        "pain": "0",
        "chiefcomplaint": "Sudden onset right-sided weakness, facial droop, and slurred speech starting 45 mins ago.",
        "is_returning_patient": True,
        "prior_medical_history": "Hypertension, Atrial Fibrillation"
    },
    {
        "stay_id": 3005,
        "subject_id": 1005,
        "name": "Marcus Vance (Cardiac - Crushing Chest Pain)",
        "age": 54,
        "gender": "Male",
        "temperature": 98.2,
        "heartrate": 110,
        "resprate": 22,
        "o2sat": 96,
        "sbp": 158,
        "dbp": 94,
        "pain": "9",
        "chiefcomplaint": "Crushing substernal chest pain radiating to left arm and jaw accompanied by diaphoresis and nausea.",
        "is_returning_patient": True,
        "prior_medical_history": "Hyperlipidemia, 30 pack-year smoking history"
    },
    {
        "stay_id": 3012,
        "subject_id": 1012,
        "name": "Carlos Gomez (Abdominal Pain / Appendicitis)",
        "age": 31,
        "gender": "Male",
        "temperature": 100.2,
        "heartrate": 96,
        "resprate": 18,
        "o2sat": 99,
        "sbp": 130,
        "dbp": 82,
        "pain": "8",
        "chiefcomplaint": "RLQ abdominal pain, severe rebound tenderness, nausea and vomiting for 12 hours.",
        "is_returning_patient": True,
        "prior_medical_history": "No major chronic illnesses"
    },
    {
        "stay_id": 3015,
        "subject_id": 1015,
        "name": "Lisa Cuddy (Ankle Injury - ESI 4)",
        "age": 38,
        "gender": "Female",
        "temperature": 98.4,
        "heartrate": 72,
        "resprate": 16,
        "o2sat": 100,
        "sbp": 120,
        "dbp": 76,
        "pain": "4",
        "chiefcomplaint": "Twisted left ankle while jogging, mild swelling, able to ambulate with limp.",
        "is_returning_patient": False,
        "prior_medical_history": "First-time patient"
    }
]
