from typing import List, Dict, Any

SIMULATED_PATIENTS: List[Dict[str, Any]] = [
    {
        "stay_id": 3001,
        "subject_id": 1001,
        "name": "James Wilson (Critical Trauma)",
        "age": 42,
        "gender": "Male",
        "temperature": 97.2,
        "heartrate": 138,
        "resprate": 30,
        "o2sat": 86,
        "sbp": 78,
        "dbp": 45,
        "pain": "10",
        "chiefcomplaint": "CAR VS POLE, MVC WITH FLIAL CHEST AND SEVERE HYPOXIA, RESPIRATORY DISTRESS",
        "is_returning_patient": True,
        "prior_medical_history": "No prior ED visits."
    },
    {
        "stay_id": 3002,
        "subject_id": 1002,
        "name": "Elena Rostova (Stroke / Facial Droop)",
        "age": 68,
        "gender": "Female",
        "temperature": 98.4,
        "heartrate": 92,
        "resprate": 18,
        "o2sat": 97,
        "sbp": 185,
        "dbp": 105,
        "pain": "0",
        "chiefcomplaint": "Sudden onset right-sided weakness, facial droop, and slurred speech starting 45 mins ago.",
        "is_returning_patient": True,
        "prior_medical_history": "Hypertension, Atrial Fibrillation"
    },
    {
        "stay_id": 3003,
        "subject_id": 1003,
        "name": "Tommy Vance (Pediatric Case)",
        "age": 3,
        "gender": "Male",
        "temperature": 103.8,
        "heartrate": 142,
        "resprate": 34,
        "o2sat": 95,
        "sbp": 90,
        "dbp": 55,
        "pain": "7",
        "chiefcomplaint": "3-year-old child presenting with high fever, severe lethargy, and tugging at right ear for 2 days.",
        "is_returning_patient": False,
        "prior_medical_history": "First-time patient (Zero history on file)"
    },
    {
        "stay_id": 3004,
        "subject_id": 1004,
        "name": "Arthur Pendelton (Geriatric Ambiguous Presentation)",
        "age": 79,
        "gender": "Male",
        "temperature": 97.6,
        "heartrate": 58,
        "resprate": 16,
        "o2sat": 96,
        "sbp": 134,
        "dbp": 70,
        "pain": "3",
        "chiefcomplaint": "79-year-old presenting with vague indigestion, mild fatigue, and subtle weakness since morning. Under-reporting pain.",
        "is_returning_patient": True,
        "prior_medical_history": "Coronary Artery Disease, Type 2 Diabetes"
    },
    {
        "stay_id": 3005,
        "subject_id": 1005,
        "name": "Marcus Vance (Cardiac - Crushing Chest Pain)",
        "age": 54,
        "gender": "Male",
        "temperature": 98.2,
        "heartrate": 110,
        "resprate": 22,
        "o2sat": 96,
        "sbp": 158,
        "dbp": 94,
        "pain": "9",
        "chiefcomplaint": "Crushing substernal chest pain radiating to left arm and jaw accompanied by diaphoresis and nausea.",
        "is_returning_patient": True,
        "prior_medical_history": "Hyperlipidemia, 30 pack-year smoking history"
    },
    {
        "stay_id": 3006,
        "subject_id": 1006,
        "name": "Priya Sharma (Neutropenic Fever)",
        "age": 36,
        "gender": "Female",
        "temperature": 102.4,
        "heartrate": 125,
        "resprate": 20,
        "o2sat": 98,
        "sbp": 102,
        "dbp": 64,
        "pain": "4",
        "chiefcomplaint": "Fever, Neutropenia, undergoing active chemotherapy for lymphoma.",
        "is_returning_patient": True,
        "prior_medical_history": "Hodgkin Lymphoma on CHOP regimen"
    },
    {
        "stay_id": 3007,
        "subject_id": 1007,
        "name": "David Miller (DKA - Diabetic Ketoacidosis)",
        "age": 27,
        "gender": "Male",
        "temperature": 98.0,
        "heartrate": 128,
        "resprate": 28,
        "o2sat": 98,
        "sbp": 106,
        "dbp": 62,
        "pain": "6",
        "chiefcomplaint": "DKA, Transfer from urgent care, vomiting, Kussmaul breathing, polyuria.",
        "is_returning_patient": False,
        "prior_medical_history": "Zero-history patient (First time presenting)"
    },
    {
        "stay_id": 3008,
        "subject_id": 1008,
        "name": "Robert Taylor (Gastrointestinal Bleed)",
        "age": 61,
        "gender": "Male",
        "temperature": 97.4,
        "heartrate": 118,
        "resprate": 20,
        "o2sat": 97,
        "sbp": 94,
        "dbp": 58,
        "pain": "5",
        "chiefcomplaint": "Coffee ground emesis and BRBPR (bright red blood per rectum) with dizziness.",
        "is_returning_patient": True,
        "prior_medical_history": "Peptic Ulcer Disease, Cirrhosis"
    },
    {
        "stay_id": 3009,
        "subject_id": 1009,
        "name": "Sarah Connor (Asthma Exacerbation)",
        "age": 29,
        "gender": "Female",
        "temperature": 98.6,
        "heartrate": 115,
        "resprate": 26,
        "o2sat": 91,
        "sbp": 128,
        "dbp": 82,
        "pain": "0",
        "chiefcomplaint": "Acute asthma attack, severe dyspnea, wheezing, albuterol inhaler ineffective.",
        "is_returning_patient": True,
        "prior_medical_history": "Severe Persistent Asthma"
    },
    {
        "stay_id": 3010,
        "subject_id": 1010,
        "name": "Michael Chang (S/P Fall - Head Bleed)",
        "age": 72,
        "gender": "Male",
        "temperature": 98.1,
        "heartrate": 78,
        "resprate": 16,
        "o2sat": 98,
        "sbp": 162,
        "dbp": 88,
        "pain": "6",
        "chiefcomplaint": "s/p Fall down 6 stairs with head injury, lost consciousness briefly, currently on Coumadin, suspected SDH/Head Bleed.",
        "is_returning_patient": True,
        "prior_medical_history": "Atrial Fibrillation on Warfarin"
    },
    {
        "stay_id": 3011,
        "subject_id": 1011,
        "name": "Hannah Abbott (Suicidal Ideation)",
        "age": 22,
        "gender": "Female",
        "temperature": 98.4,
        "heartrate": 88,
        "resprate": 16,
        "o2sat": 99,
        "sbp": 118,
        "dbp": 76,
        "pain": "0",
        "chiefcomplaint": "SI (Suicidal ideation) with intent, voluntary walk-in requesting psychiatric evaluation and safety hold.",
        "is_returning_patient": False,
        "prior_medical_history": "First-time patient (Zero history)"
    },
    {
        "stay_id": 3012,
        "subject_id": 1012,
        "name": "Carlos Gomez (Abdominal Pain / Appendicitis)",
        "age": 31,
        "gender": "Male",
        "temperature": 100.2,
        "heartrate": 96,
        "resprate": 18,
        "o2sat": 99,
        "sbp": 130,
        "dbp": 82,
        "pain": "8",
        "chiefcomplaint": "RLQ abdominal pain, severe rebound tenderness, nausea and vomiting for 12 hours.",
        "is_returning_patient": True,
        "prior_medical_history": "No major chronic illnesses"
    },
    {
        "stay_id": 3013,
        "subject_id": 1013,
        "name": "Dorothy Gale (Cellulitis - Missing Vitals Signal)",
        "age": 65,
        "gender": "Female",
        "temperature": None,  # Missing temperature
        "heartrate": 84,
        "resprate": 16,
        "o2sat": None,  # Missing SpO2
        "sbp": 138,
        "dbp": 80,
        "pain": "7",
        "chiefcomplaint": "Right lower leg redness, warmth, swelling, spreading cellulitis.",
        "is_returning_patient": True,
        "prior_medical_history": "Venous Insufficiency"
    },
    {
        "stay_id": 3014,
        "subject_id": 1014,
        "name": "Kevin Bacon (Kidney Stone / Flank Pain)",
        "age": 48,
        "gender": "Male",
        "temperature": 98.6,
        "heartrate": 104,
        "resprate": 20,
        "o2sat": 99,
        "sbp": 145,
        "dbp": 90,
        "pain": "10",
        "chiefcomplaint": "Sudden severe right flank pain radiating to groin, dysuria, hematuria, writhing in pain.",
        "is_returning_patient": True,
        "prior_medical_history": "Nephrolithiasis"
    },
    {
        "stay_id": 3015,
        "subject_id": 1015,
        "name": "Lisa Cuddy (Ankle Injury - ESI 4)",
        "age": 38,
        "gender": "Female",
        "temperature": 98.4,
        "heartrate": 72,
        "resprate": 16,
        "o2sat": 100,
        "sbp": 120,
        "dbp": 76,
        "pain": "4",
        "chiefcomplaint": "Twisted left ankle while jogging, mild swelling, able to ambulate with limp.",
        "is_returning_patient": False,
        "prior_medical_history": "First-time patient"
    },
    {
        "stay_id": 3016,
        "subject_id": 1016,
        "name": "Gregory House (Medication Refill - ESI 5)",
        "age": 52,
        "gender": "Male",
        "temperature": 98.6,
        "heartrate": 68,
        "resprate": 14,
        "o2sat": 99,
        "sbp": 118,
        "dbp": 74,
        "pain": "1",
        "chiefcomplaint": "Ran out of blood pressure prescription medication, requesting 3-day refill, no active complaints.",
        "is_returning_patient": True,
        "prior_medical_history": "Essential Hypertension"
    }
]
